export const Strings = {
    title: 'Ut ac felis mauris. Maecenas eu semper enim.',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend nisl sapienante nulla, non feugiat augue',
    feedBack: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus elit nec elit convallis hendrerit. Praesent a ultrices ligula. Mauris vulputate ornare felis ac semper. Aliquam erat volutpat. Integer massa sapien, bibendum eu pretium eget, tempor sit amet tortor. Nullam aliquam hendrerit risus. Sed a convallis nulla. ',
    privacyPolicy: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pulvinar volutpat amet, elementum. Libero, placerat mauris sodales etiam pellentesque. In blandit sit blandit egestas arcu porttitor sollicitudin. Vel eget pulvinar feugiat orci at. Dignissim nisi, at lectus nulla. Nunc vel aliquet enim ut dignissim morbi in maecenas. Nisl fringilla semper dui scelerisque. Quis vestibulum dapibus amet turpis. Ullamcorper lorem sapien commodo etiam facilisis lorem urna at. Turpis massa faucibus quisque ut orci, nunc tellus mauris non. Pellentesque enim quisque faucibus turpis lectus justo, ut in. Elit ullamcorper vivamus nulla vestibulum, penatibus habitasse. A, ipsum vel lectus amet, molestie mi, integer malesuada est. Nec netus non tortor nunc. Mus enim, placerat vel diam nulla etiam egestas fringilla justo\n\nMauris gravida mi, neque non a consectetur magna nunc ullamcorper. Felis ante quisque eget enim, nec. Nec fames morbi sodales volutpat rhoncus sollicitudin fermentum tortor sed. Tempor facilisis vulputate arcu metus lobortis ut nunc fringilla. Amet amet malesuada lectus praesent egestas sit ut.  Ullamcorper lorem sapien commodo etiam facilisis lorem urna at. Turpis massa faucibus quisque ut orci, nunc tellus mauris non. Pellentesque enim quisque faucibus turpis lectus justo, ut in. Elit ullamcorper vivamus nulla vestibulum, penatibus habitasse. A, ipsum vel lectus amet, molestie mi, integer malesuada est.\n\nUllamcorper lorem sapien commodo etiam facilisis lorem urna at. Turpis massa faucibus quisque ut orci, nunc tellus mauris non. Pellentesque enim quisque faucibus turpis lectus justo, ut in. Elit ullamcorper vivamus nulla vestibulum, penatibus habitasse. A, ipsum vel lectus amet, molestie mi, integer malesuada est.`,
    deleteAccount: `We're sorry to see you go. If you're sure you want to delete your Jokely account, please be aware that this action is permanent and cannot be undone. All of your personal information, including your jokes and settings, will be permanently deleted.\nIf you're having trouble with your account or have concerns, please reach out to us at [contact email or support page] before proceeding with the account deletion. We'd love to help you resolve any issues and keep you as a valued Jokely user.`,
    deleteAccountInfo: `To delete your account, please enter your password in the field below and confirm your decision by clicking the 'Delete My Account' button.`,
    verificationForDelete: `For added security, we'll send an OTP code to your registered mobile number. Please enter the code in the field below to confirm your account deletion.`,
    rewardDescription:`Please consider additional gratuity for your excellent service today! 100% of tips go to the driver and helper`,
    rewardNote:`Tip calculated as 2x (driver), 1x per helper, example: driver an two helpers, driver gets $50 and each helper receives $25`
}
